### PR TITLE
Added the APOD object parser +fixed some MD022  and MD005 issues

### PR DESCRIPTION
**Pull request by akionsight**
added the APOD parser. for more info
check the APOD parser's github page
[https://github.com/akionsight/APOD](url)

fixed some MD022 and MD005 issues in the README.md

### CODE REVIEW

**Comment by akionsight** [comment]
Can you mention the module which is raising unused import

**Comment by akionsight** [comment]
the unused import for `urllib` has been removed

**Comment by akionsight** [comment]
will this pull request be merged ?

**Comment by JustinGOSSES** [comment]
Hi @akionsight can you describe what you view as the reason for your code contribution? I want to make sure I understand how you see if relating to the existing code base.

Are you trying to provide a python file to call the APOD API that exists on api.nasa.gov directly in python and parse the returned object without having standing up the API itself?

**Comment by akionsight** [comment]
> Hi @akionsight can you describe what you view as the reason for your code contribution? I want to make sure I understand how you see it relating to the existing code base.
> 
> Are you trying to provide a python file to call the APOD API that exists on api.nasa.gov directly in python and parse the returned object without having standing up the API itself?

Hi @JustinGOSSES,
I have created a python file that will help a user to quickly get and parse the information the data provided by the APOD API without spending additional time making a system like that. This will **NOT** interfere with the existing code base and is independent. It is also not the APOD API itself but it is a parser for the APOD api. It will parse the returned object without having standing up the API itself and It will not exist on api.nasa.gov.

**Comment by JustinGOSSES** [comment]
Thank you. Can you add a description like that and maybe a few lines of examples of how to use it to the readme and commit those changes to this pull request. There's a risk of confusion here, but I think it will be fine as well as things are explained well in the README.

**Comment by akionsight** [comment]
done

**Comment by akionsight** [comment]
> Thank you. Can you add a description like that and maybe a few lines of examples of how to use it to the readme and commit those changes to this pull request. There's a risk of confusion here, but I think it will be fine as well as things are explained well in the README.

Done !!

**Comment by JustinGOSSES** [comment]
Looking good. I only had time to take a quick look tonight. I'll clone and run the code on Monday or Tuesday and will likely merge it afterwards. 

Only one more request. Can you move the documentation that is currently on your repository to this fork as well? I totally get wanting to link back to your github account. Unfortunately, the US federal government has policies against "endorsing". Having some of the instructions for a repository on your site is probably treading too close to that line. As a compromise, I could call out external contributors under the "Authors" section of the README and link to https://github.com/nasa/apod-api/graphs/contributors . After the merge request, you'll be listed there.

**Comment by akionsight** [comment]
> Looking good. I only had time to take a quick look tonight. I'll clone and run the code on Monday or Tuesday and will likely merge it afterwards.
> 
> Only one more request. Can you move the documentation that is currently on your repository to this fork as well? I totally get wanting to link back to your github account. Unfortunately, the US federal government has policies against "endorsing". Having some of the instructions for a repository on your site is probably treading too close to that line. As a compromise, I could call out external contributors under the "Authors" section of the README and link to https://github.com/nasa/apod-api/graphs/contributors . After the merge request, you'll be listed there.

I totally understand that. I have now moved the `apod_object_parser` into a separate folder which also contains the` README.md` for the `apod_object_parser`. the folder is named `apod_parser`

**Comment by akionsight** [comment]
this is some code to quickly test it out
```python
import apod_object_parser

data = apod_object_parser.get_data(##your api key)
# print(data)
title = apod_object_parser.get_title(data)
exp = apod_object_parser.get_explaination(data)
media_type = apod_object_parser.get_media_type(data)
date = apod_object_parser.get_date(data)
hdurl = apod_object_parser.get_hdurl(data)
url = apod_object_parser.get_url(data)
ser_version = apod_object_parser.get_service_version(data)

print(title, "\n", exp, "\n", media_type, "\n", date, "\n", hdurl, "\n", url, "\n", ser_version, "\n")

apod_object_parser.download_image(url, date)
apod_object_parser.convert_image(date)

```

**Comment by akionsight** [comment]
will this PR be merged?

**Comment by JustinGOSSES** [comment]
Sorry for the delay. Other things offline were/are on fire. Adding to the thread so it doesn't get lost.

**Comment by JustinGOSSES** [comment]
Apologies for the delayed review. I played around with it locally and made some very small edits to documentation. Looks good.

**Pull request merged**
