### PR TITLE
resolve stack trace from being raised if a 404 is triggered (and caus…

### PR DESCRIPTION
**Pull request by AaronRobson**
…ing a 500 return)

For example in the case of the browser requesting a favicon:
(env) aaron@earl:~/code/apod-api$ python apod/service.py
 * Serving Flask app "service" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [29/Aug/2019 23:43:17] "GET / HTTP/1.1" 200 -
ERROR:service:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/aaron/code/apod-api/env/local/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aaron/code/apod-api/env/local/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aaron/code/apod-api/env/local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/aaron/code/apod-api/env/local/lib/python2.7/site-packages/flask/app.py", line 1815, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/aaron/code/apod-api/env/local/lib/python2.7/site-packages/flask/app.py", line 1743, in handle_http_exception
    return handler(e)
  File "apod/service.py", line 268, in page_not_found
    LOG.info('Invalid page request: ' + e)
TypeError: cannot concatenate 'str' and 'NotFound' objects
INFO:werkzeug:127.0.0.1 - - [29/Aug/2019 23:43:17] "GET /favicon.ico HTTP/1.1" 500 -

### CODE REVIEW

**Comment by AaronRobson** [comment]
Please note that there are a number of unrelated whitespace cleanups due to my text editor's default settings.

**Comment by AaronRobson** [comment]
I hadn't realised that @Calibrator had already got a fix for this, once that is merged I will rebase this on top to pick up my unit test to guard against regression.

**Comment by JustinGOSSES** [comment]
FYI - code was reorganized a little to make it run nicely on new server setup on AWS...  Appreciate any help re-adding these changes to the code.

**Comment by AaronRobson** [comment]
@JustinGOSSES, I've redone the change based on the new structure.
I have manually verified that my browser doesn't cause an exception to be raised when it attempts to retrieve a non-existent `/favicon.ico`.

However I've had some difficulties verifying the unit test functions correctly. I've been unable to run it or the existing tests (due to import errors).
Might I have some assistance checking that they work?

**Comment by JustinGOSSES** [comment]
tests need redone

**Comment by JustinGOSSES** [comment]
Approving as the fix to favicon works. 

A wider fix to tests is needed but I won't let ie hold up this improvement.

**Pull request merged**
